### ISSUE TITLE
Rule min-chained-call-depth conflicting with newline-per-chained-call

### ISSUE THREAD

**Issue by guipfernandes** [croct-tech/coding-standard-js#119]
## 🐞 Bug report
The rule min-chained-call-depth has conflicted with newline-per-chained-call in some scenarios.

### Steps to reproduce

1. Below there are some cases
![image](https://user-images.githubusercontent.com/25726264/159783196-2699136c-2623-4f98-9c41-4c31ba0f6b83.png)
![image](https://user-images.githubusercontent.com/25726264/159783381-3aabf98f-fd3c-46e7-a68e-42a4cc76cf80.png)
![image](https://user-images.githubusercontent.com/25726264/159783909-470e42af-e258-4ab4-acc4-716b99ee2aa0.png)
![image](https://user-images.githubusercontent.com/25726264/159982723-0a370766-7c8a-4c88-a2f1-06ecbe071ac6.png)

2. When put the call method in same line, newline-per-chained-call does not allow
![image](https://user-images.githubusercontent.com/25726264/159783567-55a056c5-3bcd-44fe-a841-3d9f2af3518f.png)
![image](https://user-images.githubusercontent.com/25726264/159783817-0de609d4-92a3-4fc9-91e0-34e87b4aeee0.png)
![image](https://user-images.githubusercontent.com/25726264/159783951-ef8487aa-c618-4ef1-b673-e6d0ebb41700.png)
![image](https://user-images.githubusercontent.com/25726264/159982847-dff84b95-3510-44db-9324-1112ec841a45.png)

### Expected behavior
Show the ESLint error: Unexpected line break. (@croct/min-chained-call-depth) on the right scenarios

**Comment by georgekaran** [comment]
Closed by #130
